.Dd $Mdocdate$
.Dt CAN
.Os
.Sh NAME
.Nm Can
.Nd F* library to manage content-addressable networks.
.Sh PROTOCOL
These are the types of messages defined
.Bl -tag
.It Vt Heartbeat
It's a message periodically sent from a peer to all its
neighbors. Each heartbeat contains the list of the peer that surrounds
him.
.It Vt Join
It's a message sent from a node (A) that
.Sy isn't part yet
of the network to a node (B) of the network. A pick a random point in the space and send a
.Vt Join
to B with that point. We have two options:
.Bl -tag
.It B owns the zone that contains the point wanted by A
In this case B can do two things:
.Bl -bullet
.It
If one of the B neighbors owns a
.Sy bigger
zone, forward the
.Vt Join
to him.
.It
or he can split its zone and telling the sender of the fact. (Note
that the sender may or may not be A)
.El
.It B does not own that zone
In this case B (without notice) forward the
.Vt Join
to the nearest node.
.El
.It Vt Split
Can only be sent as a reply to a
.Vt Join .
The sender has allocated half of its zone for the new node.
.El

.\" TODO: Get & Put
